edition = "2021"

# This value is not related to religious or mathematical reasons.
# It's calculated by subtracting the widths of the left side bar, half the width of the editor,
# and the minimap within VSCode, which is running on a 2,560-pixel-wide screen, resulting in exactly 108.
max_width = 108

newline_style = "Auto"
tab_spaces = 2
reorder_modules = true
reorder_imports = true

use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
